version: '3.8'

services:
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Forward container port 3000 to host port 3000
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: gap
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" # Forward container port 5432 to host port 5432
